### ISSUE TITLE
vim-jpに開発中のパッチを一覧できるページを追加できないか

### ISSUE THREAD

**Issue by Shougo** [vim-jp/vim-jp.github.io#102]
現在、vim-jp/issuesにていくつかのパッチが開発されています。
その中には既に本体に取り込まれたものと、取り込まれていないものとがありますがパッチを当てるために該当するIssuesを追うのは非常に大変になっています。
開発中のパッチを試してくれる人を増やすためにも、vim-jpから簡単にパッチの場所に飛べると良いのではないでしょうか。できれば、パッチの概要と現在の進捗状況も簡単にわかると良いですね（例：本体に取り込まれた、却下された等）。
誰もやる人がいなければ、私がやります。

コンテンツとしてほしいもの：

* パッチの概要
* 作者
* 最新パッチのURL
* Issuesの該当ページ
* パッチの開発状況
* vim_devに送ったか？その回答は？取り込まれたか？ToDoリストに入ったか？

ページのメンテナンスがネックになりそうなので、うまく皆で分担していきたいです。

**Comment by crazymaster** [comment]
やはり人力だとメンテナンスが...
ひとまず自動化されるまでは下のリンクを紹介するだけにしておきませんか？
https://github.com/vim-jp/issues/issues?labels=status%2Fpatched&page=1&state=open
https://github.com/vim-jp/issues/issues?labels=status%2Fsent+patch&page=1&state=open

**Comment by mattn** [comment]
http://vim-jp.org/issues/

これ改造すればいけると思う。

https://github.com/vim-jp/issues

**Comment by mattn** [comment]
http://vim-jp.org/docs/patches_list.html

これメンテしないといけない感じ？人的リソースしんどそうなら閉じちゃってもいいかと。

**Comment by mattn** [comment]
https://api.github.com/repos/vim-jp/issues/issues?labels=status/patched

これで `status/patched だけ持ってこれるけど、タイトルがパッチ一覧というコンテキストには向いてなかったりするのでアレ

**Comment by tyru** [comment]
機能と改善と修正を分けて機能だけ表示したらいい感じになる気もしますね。

**Comment by koron** [comment]
閉じましょう。

> 誰もやる人がいなければ、私がやります。

にも関わらず実施されていませんので、本質的には不要ということで。

**Comment by koron** [comment]
仮にやるなら _data/ 下に patches.yml みたいなの作って
それを表示するページを用意するってことですね。

**Comment by mattn** [comment]
@crazymaster ++

そうですよね。それでいいと思います。
