### ISSUE TITLE
VimmersページのTwitter API 1.1対応

### ISSUE THREAD

**Issue by h-east** [vim-jp/vim-jp.github.io#104]
https://github.com/vim-jp/vim-jp.github.com/issues/93#issuecomment-19460743
> あれ？久しぶりにVimmersアクセスしたら9割方の人のアイコンが表示されないです。
ブラウザでリロードしても状況は変わらず。これって「IP毎のAPI呼び出し制限」関係？なわけないですよねｗ

　
> たんにtwitter apiの1が3日前に廃止されたからだと思います。URLを1.1にしたら動くはず。

URLを1.1に変えたけどダメだった。 3b21eca8e0
imageの取得方法を変更しないといけないみたい。→ https://dev.twitter.com/docs/user-profile-images-and-banners
javascript文法やsandboxで動作確認する方法等分からなかったので、どなたか対応お願いします。

**Comment by koron** [comment]
スクレイピングして_data にURL他を突っ込んじゃうのが良さ気。
で、時々更新する感じで。

だが…やる価値があるかは微妙。
とりあえず 2016/05/15 まで動きがなかったら、閉じちゃうべきではないでしょうか。

**Comment by mattn** [comment]
scripts/update_vimmer_icon.rb もしくは scripts/update_vimmer_icon.go を実行すれば更新されたかと思います。

**Comment by koron** [comment]
え。じゃあこのissueもう要らない? やってみるか。

**Comment by koron** [comment]
$ go get github.com/PuerkitoBio/goquery
    $ go run scripts/update_vimmers_icon.go

で vimmers/vimmers.json が更新されるが、データ自体は http://vim-jp.herokuapp.com/vimmers からもってきてるので、意味なかった (´・ω・`)
統合せなあかん。

**Comment by mattn** [comment]
http://vim-jp.herokuapp.com/vimmers は JSONP にするだけしかやってないっす。なので vimmers/vimmers.json を更新すればok。

**Comment by koron** [comment]
ああ、つまりマスターデータは vimmers/vimmers.json のほうなんですね。
とりあえず更新してcommit しちゃいます。

**Comment by koron** [comment]
なおった! ありがとうございます!

**Comment by koron** [comment]
ということで閉じます。
