### ISSUE TITLE
デザイナーの観点からサイトを見直して欲しい

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-jp.github.io#13]
僕が即興で作ったサイトなので出来ればデザイナーの方等に診断して欲しい。

http://twitter.com/#!/ynkdir/statuses/115822692145430528

> ynkdir: Vim大好きなデザイナーさんで適度にひまをもてあましてるそんな都合のいい人いないかしら。今のデザインに不満があるわけでわないが。OSSコミュでWebデザイナーとして関わってるって話は聞いたことないので素朴な疑問。 |01:20 午前 9 20, 2011|

**Comment by ujihisa** [comment]
このスレに今気づいた・・・知り合いのVim好きなデザイナさん、一体誰だろう・・しまった・・・。

**Comment by ujihisa** [comment]
3年たっても思い出せないので挫折
