### ISSUE TITLE
vim-users.jp の過去記事掲載について

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-jp.github.io#133]
vim-users.jp のドメインが失効した様です。
過去記事ですがなかなか良い物もあり、出来れば復元してあげたいと思っています。

私のほうで webarchive から拾い、jekyll のポスト形式(本文とヘッダ)に復元しましたが、私の単独で決めるのはどうかと思いましたので、以下アンケートを取りたいと思います。

:+1: (`:+1:`)もしくは :-1: (`:-1:`)でお答えください。ご意見も募集します。

間違ったので issue 再登録しました。
https://github.com/vim-jp/issues/issues/571

vim-users.jp の執筆者は以下の通り。
ただし author 表記を使っている人しか抜けてません。ご了承ください。

以下、承諾者

- [ ] from_kyushu
- [x] kana
- [x] mattn
- [x] Sixeight
- [x] Shougo
- [x] Sora Harakami
- [x] t9md
- [x] thinca
- [x] tsukkee
- [x] tyru
- [x] ujihisa
- [ ] ukstudio

**Comment by raa0121** [comment]
http://vim-users.jp/2010/01/vim-10-levels/
これを復元したいんですが、 @mattn さんお願いできますか？

**Comment by mattn** [comment]
http://vim-jp.org/vim-users-jp/2010/01/13/Vim-10.html

**Comment by koron** [comment]
この issue はいつまで open にしておきますか? 

私は、起票から2年が経過する 2016/06/02 までには閉じる、ことを提案します。

それまでに承諾が取れてない人の記事については
欠番にするか、別の人が新たに書きなおして差し替えるというのでいかがでしょう?

**Comment by mattn** [comment]
たぶん承諾が取れない人は今後も取れないと思います。

**Comment by h-east** [comment]
tsukkeeさんは取れそうな気がします。twitterでここ4日以内にactive(なんかtweetしている)ですので。

**Comment by mattn** [comment]
ぶつけてみました。回答来しだい僕のほうで作業しときます。

**Comment by koron** [comment]
:+1: & :bow:

**Comment by tsukkee** [comment]
:+1:
すみません、気付けていませんでした(もしくは当時気付いたことから忘れてます)m(_ _)m

**Comment by mattn** [comment]
@tsukkee あざます！

**Comment by mattn** [comment]
done
