### ISSUE TITLE
breakindent の紹介記事

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-jp.github.io#137]
取り込まれるまでに10年も掛かった breakindent について誰か記事書きませんか？

**Comment by koron** [comment]
書く人がいないまま 1年と8ヶ月 が経ってしまってます。
旬を逃した感じなので一旦閉じます。

なお外部の記事はこちらになります。

* [Vim 7.4.338 で 'breakindent' オプションが追加された](http://d.hatena.ne.jp/osyo-manga/20140625/1403707407)
* [Vimでwrapした文章もインデント出来る様になった](http://rcmdnk.github.io/blog/2014/07/14/computer-vim/)
