### ISSUE TITLE
GitHub Pages now runs Jekyll 2.2.0

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-jp.github.io#139]
https://github.com/blog/1867-github-pages-now-runs-jekyll-2-2-0

* Sass/CoffeeScript が使える様になった
* Kramdown がデフォルトになった
* いろんなコレクションが使える様になった
* JSON でデータを保持できるようになった(サーブするという意味ではなくliquidから使う)

なんか出来るようになったはずなので、皆で考えよう。

**Comment by koron** [comment]
3.0 になってるし、起票から1年半経つし、閉じますね。
