### ISSUE TITLE
Heroku で動いている vim-jp 用サーバを非buildpackに

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-jp.github.io#161]
自分用の備忘録

**Comment by koron** [comment]
直しておきました: 「ぼうび」→「びぼう」

**Comment by mattn** [comment]
以前は third-party から go の build-pack が提供されていたけど、今は heroku 自身が出してるので本件は close にします。また現状の vim-jp.herokuapp.com も heroku 版の build-pack に置き換え済みです。
