### ISSUE TITLE
ドキュメントでの Google Code の記述を GitHub へ修正

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-jp.github.io#164]
忘備録

例: http://vim-jp.org/docs/how_to_write_patches.html

**Comment by Shougo** [comment]
:+1:

あとは、vim_dev のパッチだけでなく、Pull request も一応受けつけるようになったので、
そちらについての記述を追加するかどうかも問題ですね。

**Comment by crazymaster** [comment]
ビルド方法のページはgitに変更しました。

**Comment by Shougo** [comment]
@crazymaster ++

**Comment by crazymaster** [comment]
あの書き方だと誤爆してしまった...

パッチの書き方のページのurlをgoogle codeからbitbucketに変更しました。
本家のサイトの方でguiltの記述が追加されたらまた変更が必要そうですが...

**Comment by koron** [comment]
本件、最低限の修正は終わってると見なし、閉じます。
問い合わせが来たら再開するとしましょう。

なお `code.google` に言及している記事は、他にも以下のリストだけありましたが、
これらはブログ記事ということで、まぁ直さなくてよいか、
やるにしても注釈を追加する形で良さそうです。

```
$ jvgrep -rl code\.google .
_posts\2011-10-14-vimdoc_ja.md
_posts\2012-05-20-patch_7.3.520.md
_posts\2013-08-10-vim_7.4_released.md
_posts\2015-03-25-preparations-for-moving-to-github.md
```
