### ISSUE TITLE
コメントシステムの廃止

### ISSUE THREAD

**Issue by koron** [vim-jp/vim-jp.github.io#181]
Webサイトへのコメント(disqusやそれ以外も含め)は、廃止するという潮流があります。
そうなっている理由はいくつかありますが、まとめると以下の通りです。

*  普通のユーザはコメントをfacebookやtwitter(日本ならはてブも含む) などのSNSに残す
*  かといってそれらのSNSが提供するwidgetをimposeするとデザイン上の制約になる
*  またコンテンツの一部として見た時に、コメントが不適切になりやすい

よって http://vim-jp.org においてもコメントシステムの廃止(=disqusの利用停止)を提案します。
target date は 2016/03/31 あたりでどうでしょうか。

参考: [ウェブサイトの「コメント機能」が終わりを告げようとしている (WIRED)](http://wired.jp/2015/10/13/end-of-comment/)

**Comment by syui** [comment]
個人的には、廃止は賛成です。

理由としては、コメントが付いてる記事をあまり見かけたことがないからという理由と、Disqusは、表示速度を遅くし、かつコメント部分がごちゃごちゃしている印象を受けるので、あまり好きではないというのがあります。

上記の文章を分かりやすくまとめると以下のとおりになります。

## 問題提起

コメントシステムの廃止(=disqusの利用停止)に賛成か反対か

## 結論

賛成

## 賛成する主な理由

- コメントが大量に付いているのなら反対するかもしれませんが、現状ではその傾向は見られない

- Disqusはデザイン上の制約がある

**Comment by crazymaster** [comment]
:+1:

**Comment by tyru** [comment]
:+1:

**Comment by h-east** [comment]
:+1: バレンタインデーもしくは2月末終了でもいいかも。

**Comment by mattn** [comment]
廃止は構いませんが、記事単位で有効に出来る方法は残してほしいです。
具体的には出版物の正誤表へのコメント欄が欲しいです。

**Comment by h-east** [comment]
@mattn どこか適切なところにIssueを立ててそのリンクを記事の後半に貼って誘導するのでも良い気がします。ダメ？

**Comment by mattn** [comment]
@h-east github のアカウント持ってないとコメント出来ないのはちょっと...

**Comment by Milly** [comment]
@h-east githubアカウント作る気ない人からも情報提供欲しいってことじゃないんでしょうか。

**Comment by mattn** [comment]
@Milly ソフトウェアのバグに対するissueの位置付けと、出版物に対する誤記の指摘はちょっと違うと思っていて、vim の本を読んでいる人なら github のアカウントを持っていて当然、というのはちょっと行き過ぎかなというのが個人的な持論です。例えば Vim テクニックバイブルの時は正誤表に付けられたコメント欄に多くコメントを貰いましたし、Vim script テクニックバイブルの時は twitter にいた人から指摘を貰いました。おそらくその方はgithubのアカウントを持っていない、単なるvimを好きな方だった印象です。コメント欄を消す事で貴重な意見が貰えなくなってしまわないかという事を危惧しています。
もちろん現状のコメント欄が殆ど機能していない(コメントをする人が減った)ので、廃止というのは当然の決断だと思います。なので「個別に有効に出来る方法」をちょこっとだけ考えておいて、程度に言ったつもりです。
あ、その部屋掃除するなら本棚の整理もお願いしていいかしら、というくらいのアレです。

**Comment by koron** [comment]
@mattn 
「書籍の誤記の指摘」のようなフィードバック内容を、コメントのようにコンテンツに貼りこむ必要はあるでしょうか?
その件で本当に必要なのは適切なフィードバックシステムであって、
コメントシステムではないという風に理解している読めるのですが
あってますか?

**Comment by koron** [comment]
\# あ、適切なフィードバック方法が見つかるまで
\# コメントシステムで代用できるようにすることについて
\# 反対しているわけではありません。

**Comment by h-east** [comment]
@mattn @Milly うーん。なるほど。。
じゃぁ、2chにスレ立ててそのリンクを～ (冗談)
でも、今時なにがしかのアカウントは取得しないとネット上で発言し難いと思います。
発信側がgithubとtwitterとfacebook +αでコメントもらえるように手段を用意したらいいと思うんです。

たった今 @koron さんも言っていますが、コメントシステム削除の件とは別の話な気がします。

**Comment by mattn** [comment]
もう一度言いますが、僕はコメント欄廃止に反対の立場では無いです。
現状、コメントシステムをこさえる程のマンパワーも無いし、かといって意見が貰える口を狭めるのも勿体ないので現状動いている(かつ過去にフィードバックを貰った事がある)コメント欄をフィードバックシステムの代用品でもいいので残しておければ、と思ったまでです。
別の物でフィードバックシステムとして機能する物があればそれでもいいです。

**Comment by mattn** [comment]
# 議論がしたい訳ではないです。

**Comment by Milly** [comment]
個人的には Twitter 連携ログインでさえ(連携していいものか確認するのが)めんどくさい場合があるので、どこかの Twitter アカウントにメンションぶん投げる程度で情報提供完了するくらいの手軽さが欲しい。
するとやっぱりコメントシステムを置いておくより各種SNSリンクボタンがあって、情報提供者が自分のアカウントで言及する→こっち側で言及を頑張って拾ってくる、というほうが適当に思えます。

話を戻して

1. 全体としてのコメント欄
  - 使われてないし無くていいのでは
2. 一部ページの情報提供窓口としてのコメント欄
  - 個別に残せるならそのままでいいのでは
3. 情報提供窓口としての手軽なフィードバックシステムについて
  - 別 issue でやる

**Comment by koron** [comment]
> 一部ページの情報提供窓口としてのコメント欄

もちろん残すようにはできるんです。ただ当初の理由の1つ

> コンテンツの一部として見た時に、コメントが不適切になりやすい

を考慮すると、残すとしても「されたコメント」をデフォルトでは表示したくはないなぁ、
となって良い方法がないか思案中。

**Comment by mattn** [comment]
現状のコメント欄もモデレート式です。
全て一旦、僕の所に来ます。

**Comment by koron** [comment]
disable-disqus-181 ブランチで、試作してみます。

**Comment by koron** [comment]
**要約**

* デフォルトで disqusの表示はオフ
* ヘッダー部分に `disqus: true` と書いたページには、コメント欄が引き続き表示される

**やったこと詳細**

* _include/disqus.html を追加した
* _layout/disqus.html は廃止した。コレを使っていたページ/レイアウトは _layout/default.html を使うように修正した
* _layout/default.html ではフラグ `page.disqus` により _include/disqus.html を `{% include %}` するようにした
  * 書籍の正誤表など、一部のページには `disqus: true` を予め設定した
* 個別に disqus を設定していたページは、基本使わないように変更した
  * そのうち幾つか(旧vimmers)では、 _include/disqus.html を `{% include %}` するようにした

**Comment by koron** [comment]
**やってみた感想**

* disqus が widget であることを考えると、 `layout: disqus` を削除して `_include/disqus.html` を追加したのは正解だった
* 正誤表以外にも、disqusを有効化したほうが良いページはないだろうか?

**Comment by koron** [comment]
あとデフォルトでは表示されずクリックしたら出てくる、みたいなウィジェットがないか探してみます。
(既存のパーツを使って作ることはできるでしょうが、使用頻度から考えると自作するほどの価値は見いだせないかな…)
![01](https://cloud.githubusercontent.com/assets/468368/13462709/f30006e0-e0cb-11e5-8896-2e274913536d.png)

**Comment by koron** [comment]
> デフォルトでは表示されずクリックしたら出てくる、みたいなウィジェットがないか

やっぱ disqus にはなかった。あったら or 作ったら教えてください。
