### ISSUE TITLE
vim-jp.github.io への名称変更

### ISSUE THREAD

**Issue by koron** [vim-jp/vim-jp.github.io#182]
もともとルートとなる github-pages は `*.github.com` だったが、
ある時点から `*.github.io` を使うようになった。
現在はその時の移行措置として両方使えるようになっているらしく
そのために元々の vim-jp.github.com がルートとして使えているっぽい。
しかし、いつ `*.github.io` だけになるかわからないので、
(そうなるとしても猶予期間はあるだろうけれど…)
あらかじめ名称を変更しておいたほうが良いのかもしれない。

変えるときに何かgithub側のバグを踏む可能性はある。

**Comment by koron** [comment]
だれか既にやって上手くできたって人がいると、助かるのだが。

**Comment by mattn** [comment]
もともと mattn.github.com というリポジトリで作った後で io になったけど、リポジトリ名を mattn.github.io にリネームしあとのコミットもちゃんと反映されました。

https://github.com/mattn/mattn.github.io

**Comment by koron** [comment]
@mattn ありがとうございます! しかも今w

**Comment by mattn** [comment]
Jekyll 3.0 でコードハイライトはかなり便利になったっぽい。

http://mattn.kaoriya.net/software/20160215110235.htm

**Comment by koron** [comment]
ええ。 rouge がデフォになりましたから、超楽です。
http://www.kaoriya.net/blog/2016/02/07/

**Comment by koron** [comment]
Done
