### ISSUE TITLE
HTTPS対応

### ISSUE THREAD

**Issue by koron** [vim-jp/vim-jp.github.io#187]
kloudsec 使って HTTPS にしてみたら、いくつか問題が出た。

*  各種外部リソース(js/css/images)を http で取ってたのでブロックされた
*  URLが変わったので、はてブやfacebookやG+がリセットされた

なんか良い方法はないだろうか?

**Comment by raa0121** [comment]
http://rcmdnk.github.io/blog/2014/12/23/blog-octopress/
とりあえず、https でもできるように改造してるのはありました

**Comment by raa0121** [comment]
http://www.ayudante.jp/column/2015-07-01/17-24/
Twitter Google+ Facebook 用です
PHPで書かれてますが、javascript でもできるはずですね

**Comment by koron** [comment]
考えなきゃいけないことがいくつかある。

* HTTPSをデフォルトにするか? 必要性がなければ、やる意味がないのかも。
* 見た目のカウンタを古いほうにすると、HTTPSデフォルト後の新規ブクマは追加されない。
* 新しい方にするとリセットされてしまう。
* 併記はわかりにくい。

**Comment by koron** [comment]
HTTPS化か、旧カウンタのどちらかを諦めたほうが、正しい気がする。

**Comment by koron** [comment]
あと kloudsec って、サービス継続できるのだろうか?

**Comment by koron** [comment]
私の検討結果なんですが、以下のとおりです。

* kloudsec を用いた HTTPS 化はしない
* github かソレに準じたplayerによる同種のサービスが登場した際には、それを使ってHTTPS化する
* HTTPS化の際は、HTTPからのリダイレクトはするが、カウンタの引き継ぎのための小細工/hackはしない
* カウンタサービス側に正規のカウント移行手段などがあれば、それを利用する
* 将来のHTTPS化を見越した、外部リソースへのアクセス方法の更新は、実際に移行するかどうかに関わらず行っておく

以上、ご意見などあれば。

**Comment by mattn** [comment]
もう一つ

* 金銭的コストは掛けない

**Comment by koron** [comment]
金銭的コストをかけるかどうかは ROI 次第、としておきたいです。

現状では、HTTPS化にコストをかけるだけのメリットを見いだせていないので、掛けないということになります。
しかし仮に将来、HTTPS化が必須かつ vim-jp にとって十分な魅力的な提案があったならば、
あらためて判断したいです。

**Comment by crazymaster** [comment]
ちなみにですけど username.github.io の方は既に https に対応してますね

**Comment by koron** [comment]
具体的に今できる仕事として #188 を作成しました。

それ以外のHTTPS化に向けた作業は現時点ではしないってことで、
本issueは閉じます。

HTTPS化が必要になった際には、reopenするか別issueを作りましょう。
