### ISSUE TITLE
Vim Magazine の自動化を考える

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-jp.github.io#189]
理想の形からすると自動化するのが良いかと思います。
例えば1月号の push が完了したら2月号の雛(例: 拡張子 .md.pre) を作り、2月号の push 時には最下部にパッチ一覧を付け足して拡張子を .md にして push する、僕らはその1か月の間に作られた雛に時事ネタを追加しておく。

出来るかどうかわからないけど。

**Comment by tyru** [comment]
自動化とは違いますが、ふと人間が手動でキャッチアップする必要がありそうな情報を何となくまとめてたのでご参考までにどうぞ。
(重複もかなりあると思いますしフィルタリングしないといけないでしょうが)

* backspacefm Vim-side
* Software Design Vimの細道
* How I Vim
* はてブの vim タグ
* イベント
  * TokyoVim
  * Yokohama.vim

**Comment by crazymaster** [comment]
月末に cron で実行するようにできれば、ほぼ自動化できそうですね。
[hub](https://github.com/github/hub)というコマンドラインツールがあるので、
現在のmagazineブランチ + Pull req運用でもいけそう。
時事ネタと新機能はマージまでに追加しておくということで。

**Comment by koron** [comment]
no longer valid
