### ISSUE TITLE
Patch 7.4.1577 の問題を周知する

### ISSUE THREAD

**Issue by tyru** [vim-jp/vim-jp.github.io#190]
http://lingr.com/room/vim/archives/2016/03/21#message-23149400

> thinca: Portage の Vim のメンテナ、1577 のやばさを一切理解していないらしく、7.4.1583 という微妙なバージョンをリリースしている

> anekos: Arch Linux は、7.4.1584 がリリースされてる!

> thinca: Arch Linux のメンテナも Vim よくわかってない人かー

ローリング・リリースのOSではすでに 7.4.1577 (or higher) な Vim がリリースされちゃってるようです。
vim-jp.org でも何か告知が必要ではないでしょうか。
(自分は Jekyll 分かってなくてすぐ書けない…すみません)

**Comment by ujihisa** [comment]
長期間アプデの入らないubuntuのLTSやredhat系のそれに1577+が入ってしまうとやばそう

**Comment by thinca** [comment]
http://vim-jp.org/blog/2016/03/23/take-care-of-patch-1577.html
ものすごく細かい指摘で申し訳ないんですが、Partial 自体が入ったのは 7.4.1559 です。
7.4.1577 で入ったのは、辞書関数にアクセスすると、辞書を `self` として bind した Partial を返すようにする機能ですね。
あとこの Partial はカリー化ではないです。

**Comment by mattn** [comment]
すいません。時間ないので直してもらえると助かります。

**Comment by thinca** [comment]
私も今は時間がないので、あとで時間あったらやります。(うまくまとめられる自信がないので誰かやってくれても良いです)

**Comment by koron** [comment]
やりました。 reopen しておいてくれたら嬉しかったw

**Comment by thinca** [comment]
すいません & ありがとうございます！
そしてすいません。私がはっきり言わなかったのが悪いのですが、内容がまだ正確ではないです…。修正 PR あとで投げます。 :bow:

**Comment by tyru** [comment]
自分からもさらに #193 投げました。

**Comment by mattn** [comment]
http://vim-jp.org/blog/2016/03/23/take-care-of-patch-1577.html#comment-2587024486

**Comment by tyru** [comment]
追記しました。 7c46bfe84e677d1bdc834ae0de63183ba50d555a

**Comment by koron** [comment]
Could this issue be closed?

**Comment by tyru** [comment]
ありがとうございました。
