### ISSUE TITLE
いいねボタンが一瞬改行されている

### ISSUE THREAD

**Issue by koron** [vim-jp/vim-jp.github.io#206]
リロードすると _includes/sns-badges.html 内の **いいねボタン** が
一瞬だけ改行して表示される。

HTML+CSSで対応できないだろうか?

**Comment by mattn** [comment]
たぶん facebook widget の `display: inline-block` がスクリプトで非同期に設定されてるので、あらかじめ `.fb_iframe_widget` を `display: inline-block` にしてしまえば治る気がする。

**Comment by koron** [comment]
facebookだけじゃなくて他のwidgetもいつそうなるかわからないので、まとめてそれやっちゃうのが良いかなって考えてます。
