### ISSUE TITLE
reading vimrc 4周年 記事を書く

### ISSUE THREAD

**Issue by koron** [vim-jp/vim-jp.github.io#213]
どうやら 7/9 で reading vimrc が4周年を迎えるらしいです。

それを伝える、祝う記事を書き、7/9 (もしくは 7/2) に掲載します。
同時に vim magazine 7月号のネタとします。

**Comment by mattn** [comment]
ごいすー

**Comment by koron** [comment]
reminder.

**Comment by koron** [comment]
continue to #215
