### ISSUE TITLE
MinGWを使ってのビルド方法 ページの改善提案

### ISSUE THREAD

**Issue by h-east** [vim-jp/vim-jp.github.io#216]
http://vim-jp.org/docs/build_windows_mingw.html

上記ページの最後の方に

```
注意2) ARCH は i686 または x86-64 を指定して下さい。
```

が記述されていますが、これは「4. コンパイル」の冒頭に持ってくるべきだと感じました。
(私自身ビルドエラーが出たためこのページを最後まで読まずにググってしまって解決後に気付きました:sweat:)
今時はほとんどが64bitなので`ARCH=x86-64`を付けてもいいのではないかと思います。

```
mingw32-make -f Make_ming.mak GUI=yes IME=yes MBYTE=yes ^
  ICONV=yes DEBUG=no ARCH=x86-64
```

その上で以下の注釈をつければ良いと思いました。
※32bitの場合は`ARCH`に`i686`を指定下さい。

いかがでしょう？

**Comment by k-takata** [comment]
64bitコンパイラを使ってARCHを指定しなかったということでしょうか。現状のMakefileは32bit向けがデフォルトですからね。
最初に持って行った方がいいというのはそうかもしれません。
（本当はARCH無指定で行ければ楽なのですが。）

**Comment by h-east** [comment]
> 64bitコンパイラを使ってARCHを指定しなかったということでしょうか。

はい、そうです。

Makefileを64bitデフォルトにするというのもありですね。

**Comment by nocd5** [comment]
```make
ifndef ARCH
ARCH=$(shell uname -m)
endif
```
はどうでしょう?
クロスビルド用に外から設定できるようにはしておいて欲しいです。

**Comment by k-takata** [comment]
`$(CC) -dumpmachine` を元に、今使っているコンパイラのデフォルト値を使ったほうが良い気がします。

> Makefileを64bitデフォルトにするというのもありですね。

いまだに公式バイナリが32bitであることを考えると、まだ早そう。

**Comment by k-takata** [comment]
投げました。
https://groups.google.com/d/topic/vim_dev/FXAec_z8Xjg/discussion

**Comment by k-takata** [comment]
7.4.2030
https://groups.google.com/d/topic/vim_dev/-0Y6hrFBA_k/discussion

**Comment by h-east** [comment]
@k-takata  私もこの人と同じくらいに「あれ？」ってなったとこです。
https://groups.google.com/d/msg/vim_dev/-0Y6hrFBA_k/D97D0bvLAAAJ

**Comment by k-takata** [comment]
7.4.2032
https://groups.google.com/d/topic/vim_dev/hP9vtQcba30/discussion
