### ISSUE TITLE
HTTPS化検討再び

### ISSUE THREAD

**Issue by koron** [vim-jp/vim-jp.github.io#231]
CloudFlare という player が出てきてた。

https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

預けるに値するか、要検討。

---

前 issue #187 からの残件

* HTTPS化の際は、HTTPからのリダイレクトはするが、カウンタの引き継ぎのための小細工/hackはしない
* カウンタサービス側に正規のカウント移行手段などがあれば、それを利用する
* 金銭的コストをかける場合は ROI をよく考えて

**Comment by crazymaster** [comment]
>vim-jp.org が HTTPS になりました
https://vim-jp.org/vimmagazine/2018/05/31/vimmagazine.html
