### ISSUE TITLE
octopressの使用を考慮に入れる

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-jp.github.io#24]
サーバ側の拡張でなく、記事アップする前の拡張だし、依存度が高くなるのであまりやりたくない気もあるけど
一応、考慮に入れておく

    https://github.com/imathis/octopress

**Comment by koron** [comment]
Moved to https://github.com/octopress/octopress

**Comment by koron** [comment]
これ、4年間なくても困らなかったし、動きもなかったので、閉じます。
なにより、プレビューするのに octopress の操作まで覚えてもらう必要が出てしまうので。
