### ISSUE TITLE
Vim Advent Calendar 2012/2013 のトップ絵を復活させたい

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vim-jp.github.io#362]
https://vim-jp.org/slacklog/C03C4RC9F/2020/01/#ts-1578996297.326300

2013 は Kuniwak さんから OK が出ています。
2012 は IMAGEDRIVE さんに確認が必要です。

**Comment by imagedrive** [comment]
OKです

**Comment by k-takata** [comment]
ありがとうございます。m(_ _)m

**Comment by k-takata** [comment]
復活させました。
https://vim-jp.org/docs/vac2012.html
https://vim-jp.org/docs/vac2013.html
@Kuniwak さん @imagedrive さん、ありがとうございます。
