### ISSUE TITLE
slacklogの公開とライセンスについて明記する

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/vim-jp.github.io#368]
see https://github.com/vim-jp/vim-jp.github.io/blob/master/docs/chat.md

現在最後にlogの公開のことがあるが、参加前に許可、もしくはそれに類似した確認はしたほうが(いろいろ)よさそう。

なので

> slackへ参加するとlogがCC4.0-BYで公開される

的な説明が参加リンクより前にあるとよさそう。

**Comment by tomoya** [comment]
理想的には、ログを非公開にしてほしい人の窓口を案内できると、より安心できるかと思いますが、やるとすれば別issueで良いと思いますので、ひとまずはログを公開されたくない方は、このリポジトリのissueからご連絡下さいくらいの案内で良いと思いました。

**Comment by tsuyoshicho** [comment]
いままでの人はそうですね...

これからの人は公開/CC-BYであることを了承して使ってるとして、その手間も軽減(あるいはなく)したいですね。

**Comment by tsuyoshicho** [comment]
補足はマージされました。

**Comment by heavenshell** [comment]
slacklog を閉じたので、こちらの issue も閉じます。
