### ISSUE TITLE
Vim写真を貼ろうぜ

### ISSUE THREAD

**Issue by h-east** [vim-jp/vim-jp.github.io#52]
Vimという名前の商品の写真とかを貼るスレです。
- テキストエディタVimのスクリーンショットはご遠慮下さい。
- とりあえず貼って、権利関係でNGの場合は後で削除する感じで。
- エロ禁止です。
- おっさんギャグはご遠慮下さい。

ここの写真がVim勉強会のサイト等で使ってもらえたら嬉しいな。

Vim本家の画像紹介ページ(Other Weird Vim stuff)
http://www.vim.org/weird.php

**Comment by koron** [comment]
とりあえず一定量集まったってことでcloseします。

紹介用のページは、作りたい人が作るってことで、閉じます。
