### ISSUE TITLE
Vimmers に掲載されたい、したい!

### ISSUE THREAD

**Issue by koron** [vim-jp/vim-jp.github.io#79]
[Vimmers](http://vim-jp.org/vimmers/) に掲載されても良い、この人を掲載してよという人は、ここに申告をお願いします。
- 名前 (必須)
- 連絡先 (いずれか1つ必須/複数可)
  - twitter アカウント
  - github アカウント
  - ブログなどのURL
  - vim.org の profile ページ
- 一言で紹介 (オプション)

**Comment by todashuta** [comment]
twitter, github: @todashuta

よろしくおねがいします！

**Comment by wikimatze** [comment]
Twitter. GitHub: @wikimatze
homepage: http://wikimatze.de

**Comment by mattn** [comment]
@wikimatze done. can see your self on http://vim-jp.org/vimmers/

![](http://go-gyazo.appspot.com/4bcc51d470e52d54.png)

**Comment by wikimatze** [comment]
Thanks for putting me on the list.
