### ISSUE TITLE
勉強会へのリンクページがあると良いのでは？

### ISSUE THREAD

**Issue by Shougo** [vim-jp/vim-jp.github.io#85]
vim-jpをハブサイトとして活用するにあたっては、直近のVim勉強会へのリンクページがあると良いのではないでしょうか。勉強会への参加者が増え、Vim界の活性化が期待できます。
まぁ、リンクを更新する人は必要になりますが……。
希望としては、トップからできるだけアクセスしやすいところにあると良いです。
現在、「読み物」があるページとか。

**Comment by koron** [comment]
3年近く、誰も作らないので、一旦閉じます。
必要と思う人が、作ってcommit or PR してくれたらなと。
