### ISSUE TITLE
埋め込みタイムラインからノイズを除去する

### ISSUE THREAD

**Issue by Shougo** [vim-jp/vim-jp.github.io#91]
「もうVimClipをVimと略さないで！　TLにノイズが多くてVimmerのライフはもう0よ！」

https://github.com/vim-jp/vim-jp.github.com/issues/71

の続き。
最近、埋め込みタイムラインのノイズが更に増えています。

クエリ長には制限があるらしいので、もうちょっと包括的な条件を加えたいです。
今調べたところ、Vim違いの人はほぼ女性なので、♡を多用する傾向にあるようです。
TLに「♡」があるTweetを除外できないですかね？

**Comment by 0xBADDCAFE** [comment]
http://vimclip.jp/?p=info&id=28367
思わぬ形で決着を迎えそうです。

**Comment by koron** [comment]
あ、本当に解散するんだ… タイムラインにそれらしいのあったから、気になってた。

**Comment by koron** [comment]
極論、無理。今は諦めよう。

ぶっちゃけ今の twitter widget 外す/まったく別のものに差し替えることを考えても良いかもしれない。

で、閉じます。

**Comment by 0xBADDCAFE** [comment]
vimclip.jp、相当怪しいサイトになっていてやばい…。

**Comment by tyru** [comment]
怪しさ
